{
  "name": "familienstammbaum",
  "version": "1.0.0",
  "description": "Interaktive Familienstammbaum-App",
  "author": "Christof Gasser",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-builder"
  },
  "build": {
    "appId": "com.familienstammbaum.app",
    "win": {
      "target": "nsis"
    },
    "publish": null
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.3.2",
    "jspdf": "^2.5.1",
    "html2canvas": "^1.4.1"
  },
  "devDependencies": {
    "electron": "^29.0.0",
    "electron-builder": "^24.6.0"
  }
}
